#
# OMAP Clock specific Makefile
#

obj-y	+=

obj-$(CONFIG_ARCH_OMAP4)	+= cclock44xx_data.o
obj-$(CONFIG_ARCH_OMAP3)	+= cclock3xxx_data.o
obj-$(CONFIG_SOC_OMAP2420)	+= cclock2420_data.o
obj-$(CONFIG_SOC_OMAP2430)	+= cclock2430_data.o
